[package]
name = "lunchctl"
description = "Library for convenient management of background services and startup items in macOS."
version = "0.2.2"
authors = ["Mikhael Khrustik <misha@myrt.co>"]
edition = "2021"
rust-version = "1.80"
homepage = "https://github.com/mishamyrt/lunchctl"
documentation = "https://github.com/mishamyrt/lunchctl"
repository = "https://github.com/mishamyrt/lunchctl"
license = "MIT"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
serde_derive = "1.0.219"
plist = "1.7.4"
thiserror = "2.0.16"
libc = "0.2.175"
derive_builder = "0.20"

[dev-dependencies]
rand = "0.9.2"

[lints.rust]
unreachable_pub = "warn"
unexpected_cfgs = { level = "warn", check-cfg = ["cfg(codspeed)"] }

[lints.clippy]
pedantic = { level = "warn", priority = -2 }
# Allowed pedantic lints
char_lit_as_u8 = "allow"
collapsible_else_if = "allow"
collapsible_if = "allow"
implicit_hasher = "allow"
map_unwrap_or = "allow"
match_same_arms = "allow"
missing_errors_doc = "allow"
missing_panics_doc = "allow"
module_name_repetitions = "allow"
must_use_candidate = "allow"
similar_names = "allow"
single_match_else = "allow"
too_many_lines = "allow"
needless_raw_string_hashes = "allow"
# Disallowed restriction lints
print_stdout = "warn"
print_stderr = "warn"
dbg_macro = "warn"
empty_drop = "warn"
empty_structs_with_brackets = "warn"
exit = "warn"
get_unwrap = "warn"
rc_buffer = "warn"
rc_mutex = "warn"
rest_pat_in_fully_bound_structs = "warn"
redundant_clone = "warn"
debug_assert_with_mut_call = "warn"
unused_peekable = "warn"
large_stack_arrays = "allow"
